### ISSUE TITLE
Better User Experience

### ISSUE THREAD

**Issue by grantharrison** [AlDavis612/Group11SoftwareProject#10]
<img width="1680" alt="Screen Shot 2019-04-29 at 7 52 46 PM" src="https://user-images.githubusercontent.com/36210484/56935695-6440b600-6ab8-11e9-8f00-6e049e4d53cc.png">

**Comments:**
We need to update this page to display the actual image not just the name and add functionalities for the user such as deletion and sorting.

**Comment by AlDavis612** [comment]
In trying to fix our upload page, Grant also solved this problem by merging the upload.html with the upload.php, making a much better user experience
