### ISSUE TITLE
Upload photo, but nothing happens

### ISSUE THREAD

**Issue by sgoggins** [AlDavis612/Group11SoftwareProject#14]
**Describe the bug:**

**To Reproduce:**
1. upload a photo
2. process it
3. nothing seems to happen. 

**Expected behavior:**
I am able to upload one photo at a time. It says that it is scoring the photo, but when if "finishes", there's no feedback other than zero photos processed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/379847/57305696-1d018900-70a7-11e9-98d0-10a491062f6d.png)

**Desktop (please complete the following information):**
- OS: [e.g. macOS v10.14.1]
- Browser: [e.g. firefox]

**Comment by grantharrison** [comment]
We completed this bug it occurs when there is a bad connection to the internet
